name: simple-workflow
on:
    push:
        branches:
            - main
            - 'feature/**'
            - 'dev-*'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code 
              uses: actions/checkout@v6
            - name: Get Cache Path
              id: path-cache
              run: echo "dir=node_modules" >> ${GITHUBOUTPUT}
            - name: Cach Dep
              uses: actions/cache@v5
              id: cache-id
              with:
                path: ${{ steps.path-cache.outputs.dir }}
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: instal dep 
              if: steps.cache-id.outputs.cache-hit != 'true'
              run: npm ci             
            - name: lint run
              run: npm run lint 
            - name: Test 
              run: npm run test
    build:
        runs-on: ubuntu-latest
        outputs:
            var-ar: ${{ steps.ar-var.outputs.script-file }}
        steps:
            - name: Get Code 
              uses: actions/checkout@v6
            - name: Get Cache Path
              id: path-cache
              run: echo "dir=node_modules" >> ${GITHUBOUTPUT}
            - name: Cach Dep
              uses: actions/cache@v5
              id: cache-id
              with:
                path: ${{ steps.path-cache.outputs.dir }}
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: instal dep 
              if: steps.cache-id.outputs.cache-hit != 'true'
              run: npm ci 
            - name: build Project
              run: npm build 
            - name: Get Artifact File
              id: ar-var
              run: find dist/assets/*.js -type f -printf "script-file=%f\n" >> $GITHUB_OUTPUT            
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: deploy info 
              run: |
                echo "som deploy info ..."
                ehco ${{ needs.build.outputs.var-ar }}
    

            




